config/routes.rb
Rails.application.routes.draw do

  get 'landing', to: "landing#index"
  root "landing#index"

  resources :posts
  resources :authors
  resources :users

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  STATUSES = ["draft", "published"]
  # belongs_to :user

  validates :title, presence:true, uniqueness: true 
  validates :body, presence:true
  validates :status, presence:true, inclusion: {in: STATUSES}

  scope :published, -> { where(status: "published")}
  scope :draft, -> {where(status:"draft")}
  before_create :add_title_to_body

  def add_title_to_body
    self.body = "#{title} - #{body}" 
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @users = User.all
  end

  def new

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end

  def show
  
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def update
    @post.update permitted_params
    redirect_to @post
  end

  def create
    Post.create permitted_params
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to @post
  end

private
  def permitted_params
    params.require(:post).permit :title, :body, :status
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    User.create permitted_params
    redirect_to users_path
  end

private
  def permitted_params
    params.require(:user).permit :first_name, :last_name, :middle_name, :email, :password_has
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
  def render_full_name(u)
    "#{u.first_name} #{u.last_name} "
  end
end

app/views/authors/index.html.erb
<%= @authors.each do |authors| %>
 <h4> <% authors.name %>  </h4>
<%end%>

app/views/landing/index.erb
<h1>User</h1>
<% @users.each do |u| %>
 <p> <%= render_full_name(u) %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.erb
<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <p><%= post.body %></p>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br/>

  <%= f.label :body %>
  <%= f.text_field :body %>
  
  <%= f.label :status %>
  <%= f.select :status, [["Draft", "draft"], ["Published", "published"]] %>
  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<table> 
<tr style="width: 100%">
<th>Title</th>
<th>Actions</th>
</tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td>
    <%=link_to "View", post_path(post.id) %>
    <%=link_to "Edit", edit_post_path(post.id) %>
    <%=link_to "Delete", post_path(post.id), method: "delete", "data-confirm":"Kwekkwek" %>
    </td>
  </tr>
  <%end%>
 </table>


 <%=link_to "New Post", new_post_path %> 

app/views/posts/new.html.erb
<h1>NEW SHIT</h1>

<%= form_with model: @post, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br/>

  <%= f.label :body %>
  <%= f.text_field :body %>
  
  <%= f.label :status %>
  <%= f.select :status, [["Draft", "draft"], ["Published", "published"]] %>
  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<h1>Show page</h1>
<h2> <%=@post.title%> </h2>
<p> <%= @post.body %> </p>

<%=link_to "Back", posts_path %>

app/views/users/index.html.erb

<h1>User</h1>
<% @users.each do |u| %>
  -<%= u.first_name %>, <%= u.last_name %> <br/>
<% end %>


<%=link_to "Register", new_user_path %>


app/views/users/new.html.erb
<h1>Registration</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :FirstName %>
  <%= f.text_field :first_name %> <br/>
  <%= f.label :LastName %>
  <%= f.text_field :last_name %> <br/>
  <%= f.label :MiddleName %>
  <%= f.text_field :middle_name %> <br/>
  <%= f.label :Email %>
  <%= f.text_field :email %> <br/>
  <%= f.submit %>

<% end %>